apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: hackaton
  labels:
    app: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: nicolasmartinss/hackaton-notifications:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          envFrom:
            - secretRef:
                name: notification-secrets
            - configMapRef:
                name: notification-config

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi