apiVersion: v1
kind: ConfigMap
metadata:
  name: video-config
  namespace: hackaton
data:
  SPRING_PROFILES_ACTIVE: prod

  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"

  AWS_REGION: us-east-1
  AWS_S3_BUCKET_NAME: hackathon-videos-bucket

  RABBITMQ_EXCHANGE: video.processing.exchange
  RABBITMQ_QUEUE: video.processing.queue
  RABBITMQ_ROUTING_KEY: video.processing.routing