apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: hackaton
data:
  SPRING_PROFILES_ACTIVE: "prod"

  JWT_REFRESH_TOKEN_EXPIRATION: "900000"
  JWT_ACCESS_TOKEN_EXPIRATION: "604800000"

  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:4200"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  CORS_ALLOWED_HEADERS: "*"
  CORS_ALLOW_CREDENTIALS: "true"